In [4]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=np.array(["78",78])
a

array(['78', '78'], dtype='<U21')

In [13]:
y=np.empty([3,2],dtype=int)
print(y)

[[   140707708872835 368418090347439303]
 [     2806584979894      2806584979928]
 [                16                  1]]


In [15]:
np.zeros([3,4],dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
np.ones([3,4],dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros([3,4,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((2,3),dtype=int)*48

array([[48, 48, 48],
       [48, 48, 48]])

In [25]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [28]:
np.random.rand(8,2) #size

array([[0.09947584, 0.94910751],
       [0.06502081, 0.04141668],
       [0.36631068, 0.54238191],
       [0.01485403, 0.51950417],
       [0.744579  , 0.5854111 ],
       [0.69816347, 0.54361846],
       [0.99754926, 0.45609975],
       [0.52525997, 0.62306255]])

In [29]:
np.random.randint(10,20,(4,4)) #range + size

array([[18, 11, 11, 17],
       [13, 12, 17, 14],
       [13, 11, 11, 12],
       [18, 10, 15, 17]], dtype=int32)

In [30]:
np.random.normal(1,3,(4,4)) #mean , deviation

array([[ 5.10219191,  3.61186396, -2.44412053,  4.41082336],
       [-5.49529784,  2.38333941, -4.2115062 ,  2.83328511],
       [ 2.70591155,  4.39915137,  1.6038795 ,  0.47890999],
       [ 1.01358429,  0.31938155,  0.23652164, -0.67453986]])

In [33]:
a=np.full(3,3)*9
a

array([27, 27, 27])

List to array

In [35]:
y=[1,2,3,"apple"]
y

[1, 2, 3, 'apple']

In [36]:
np.asarray(y)

array(['1', '2', '3', 'apple'], dtype='<U21')

In [38]:
i=(3,4,2,78+8j) #tuples
i

(3, 4, 2, (78+8j))

In [39]:
np.asarray(i)

array([ 3.+0.j,  4.+0.j,  2.+0.j, 78.+8.j])

In [40]:
o={5,4}
o

{4, 5}